certDir: /certs
clientCAFile: /tmp/gatekeeper/ca.crt
port: 8090
provider:
  timeout: 1
  tls:
    enabled: true
    caBundle: ""
    skipVerify: false

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault